version: '{build}'
os: Visual Studio 2017
branches:
  only:
  - master
environment:
  BUILDING_ON_PLATFORM: win
  BuildEnvironment: appveyor
skip_tags: true
skip_commits:
  files:
    - docs/*
    - CONTIBUTING.md
    - LICENSE
    - README.md
    - generate_protos.bat
    - generate_protos_macos.sh
    - generate_protos_linux.sh
    - .travis.yml
    - .gitignore
build_script:
- ps: ./build.ps1
test: off
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/skywalking/api/v2/package
  api_key:
    secure: y93uJrdiEYaeVTFxeCduQSlCussOUF4UztOyhkxyZxFnIco73J/K2rdA2QShoEuh
  skip_symbols: true
  artifact: /artifacts\/packages\/.+\.nupkg/
  on:
    branch: master
