version: 0.1.0-alpha-{build}

image: Visual Studio 2017

configuration: Release

skip_commits:
  files:
    - CONTIBUTING.md
    - LICENSE
    - README.md
    - generate_protos.bat
    - generate_protos_macos.sh
    - generate_protos_linux.sh
    - .gitignore

branches:
  only:
  - master

skip_tags: true

dotnet_csproj:
  patch: true
  file: src\**\*.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- cmd: dotnet restore

build_script:
- cmd: dotnet build -c Release
    