trigger:
- coreclr_profiler

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    git checkout coreclr_profiler
    git submodule update --init -- "src/SkyApm.Transport.Grpc.Protocol/protocol" 
    cd src/SkyApm.Transport.Grpc.Protocol
    dotnet msbuild -restore:True
  displayName: 'git checkout and submodule update'

- script: |
    cd $VCPKG_ROOT
    sudo ./vcpkg install spdlog
  displayName: 'vcpkg install spdlog'

- script: |
    sudo apt-get install clang-3.9 -y
    cd src/SkyApm.ClrProfiler
    mkdir build
    cd build
    cmake -DCMAKE_BUILD_TYPE=Release ..
    make
  displayName: 'build SkyAPM.ClrProfiler so'
 
- script: |
    cd tools
    chmod +x ./Dll.Repack.sh
    ./Dll.Repack.sh Debug
  displayName: 'Dll.Repack.sh Debug'

- script: |
    cd test/SkyApm.ClrProfiler.Trace.Test
    export CORECLR_PROFILER={cf0d821e-299b-5307-a3d8-b283c03916dd}
    export CORECLR_ENABLE_PROFILING=1
    export CORECLR_PROFILER_PATH=$(Build.Repository.LocalPath)/src/SkyApm.ClrProfiler/build/SkyApm.ClrProfiler.so
    export CORECLR_PROFILER_HOME=$(Build.Repository.LocalPath)/src/SkyApm.ClrProfiler.Trace/bin/Debug/netstandard2.0
    echo $CORECLR_PROFILER_PATH
    echo $CORECLR_PROFILER_HOME
    dotnet test SkyApm.ClrProfiler.Trace.Test.csproj
  displayName: 'dotnet test SkyApm.ClrProfiler.Trace.Test'

- script: |
    cd tools
    chmod +x ./Dll.Repack.sh
    ./Dll.Repack.sh Release
  displayName: 'Dll.Repack.sh Release'